kind: pipeline
name: default

steps:
  - name: install
    image: node:11
    commands:
      - npm install
      - npx lerna bootstrap

  - name: lint
    image: node:11
    commands:
      - npm run lint

  - name: test
    image: node:11
    commands:
      # For whatever reason, our tests hang/freeze on an open resource in Docker
      # but not on macOS. Using forceExit to workaround this until we determine
      # the underlying cause.
      - npm run test -- --forceExit
    environment:
      DATABASE_USER: postgres
      DATABASE_HOST: database
      SMTP_HOST: mail
      SMTP_PORT: 1025

  - name: backup
    image: instrumentisto/rsync-ssh
    environment:
      SSH_KEY:
        from_secret: ssh_key
      KNOWN_HOSTS:
        from_secret: known_Hosts
    when:
      branch:
        - master
    commands:
      - mkdir ~/.ssh
      - echo "$SSH_KEY" > ~/.ssh/id_ed25519
      - chmod 600 ~/.ssh/id_ed25519
      - echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
      - project="travel-funds"
      - stamp=$(date +"%Y-%m-%d @ %H:%M")
      - 'ssh drone@travelfunds.core.uconn.edu pg_dump --clean --no-owner travelfunds | ssh borg@s3.core.uconn.edu "borg create --compression lz4 -v --stats \"$project::$stamp.sql\" -"'

services:
  - name: database
    image: postgres:11.2-alpine
    ports:
    - 5432
    environment:
      POSTGRES_DB: travelfunds-test

  - name: mail
    image: mailhog/mailhog:latest
    ports:
      - 1025
